<a href="https://colab.research.google.com/github/Ervin518/Python/blob/main/lab_7/Lab7b_Python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programowanie w Python
Autor dr Aneta Polewko-Klim

## Pandas wstęp
Homepage -http://pandas.pydata.org/  
DataCamp web https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python

**Additional tutorials**

http://www.shanelynn.ie/summarising-aggregation-and-grouping-data-in-python-pandas/

### Import niezbędnych bibliotek

In [ ]:
#!pip install pandas

In [1]:
import pandas as pd  # biblioteka do obsługi danych w formie tabelarycznej/ramek danych
import numpy as np   # biblioteka do obsługi danych w macierzy, wektorów, tablic
import os  # biblioteka do obsługi plików i folderów

In [2]:
from google.colab import drive
drive.mount('/content/drive')    # podłączenie zasobów z dysku Google

Mounted at /content/drive

In [ ]:
import os
import pandas as pd
folder_path = '/content/drive/MyDrive/Colab Notebooks/data/'
data = pd.read_excel(os.path.join(folder_path, 'titanic_train.xlsx'))
print(data)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

###  Tworzenie tabel/ramek danych

In [ ]:
dr = pd.date_range('1/6/2019', periods=6)  # wektor/kolumna, generowanie wektora z dat, przedział = liczba miesięcy
dr

DatetimeIndex(['2019-01-06', '2019-01-07', '2019-01-08', '2019-01-09',
               '2019-01-10', '2019-01-11'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
s = pd.Series(np.random.randn(5), index=['A', 'B', 'C', 'D', 'E'])  # kolumna + nazwy wierszy (wartości są losowane)
s

A    0.542174
B   -2.095072
C    1.348387
D   -0.600255
E   -0.368493
dtype: float64

In [ ]:
# tworzymy ramkę danych z losowymi liczbami 6x3, nazwy wierszy (id wierszy) to wartości dr, zwróć uwagę na rozmiary
tabela1 = zawartosc = np.random.randn(6, 3)
df = pd.DataFrame(tabela1, index=dr, columns=['A', 'B', 'C'])
df

                   A         B         C
2019-01-06  0.347345 -2.332799 -1.064776
2019-01-07 -0.083265  0.819239 -0.052888
2019-01-08 -0.437924 -0.405766 -1.876283
2019-01-09 -0.044599  0.549679 -0.300191
2019-01-10  0.272141  1.114775 -0.679951
2019-01-11  0.945390  0.599619  0.530890

In [ ]:

# tworzenie wielowymiarowych ramek danych tu "kostka 3D o wymiarach 2x5x4"

import xarray as xr
ds = xr.Dataset({"foo": (("x", "y"), np.random.randn(2, 3))},
                coords={
                    "x": [10, 20],
                    "y": ["a", "b", "c"],
                    "along_x": ("x", np.random.randn(2)),
                    "scalar": 123,
},)

df = ds.to_dataframe()
df
# print(pd.__version__)
# print(np.__version__)

NameError: name 'np' is not defined

### Tworzymy przykładową ramkę danych wykorzystując słownik

In [ ]:
dictionary = {'one':[1,10,100,1000,10000],
     'two':[2,20,200,2000,2000],
     'price':['prod1','prod3','prod2','prod1','prod2']}  # wykorzystamy słownik do utworzenia odpowiedniej struktury
dictionary

{'one': [1, 10, 100, 1000, 10000],
 'two': [2, 20, 200, 2000, 2000],
 'price': ['prod1', 'prod3', 'prod2', 'prod1', 'prod2']}

In [ ]:
dfs = pd.DataFrame(dictionary)
dfs

     one   two  price
0      1     2  prod1
1     10    20  prod3
2    100   200  prod2
3   1000  2000  prod1
4  10000  2000  prod2

In [ ]:
type(dfs)  # informacje o utworzonym obiekcie

pandas.core.frame.DataFrame

In [ ]:
dfs.head(2)  # wypisuje 2 pierwsze wiersze tabeli

   one  two  price
0    1    2  prod1
1   10   20  prod3

In [ ]:
dfs.tail(3)  # pokazuje 3 końcowe wiersze tabeli

     one   two  price
2    100   200  prod2
3   1000  2000  prod1
4  10000  2000  prod2

In [ ]:
dfs.info() # podstawowe informacje o danych

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   one     5 non-null      int64
 1   two     5 non-null      int64
 2   price   5 non-null      object
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [ ]:
dfs.shape  # liczba wierszy i liczba kolumn

(5, 3)

In [ ]:
dfs.columns # wyswietla nazwy kolumn tabeli

Index(['one', 'two', 'price'], dtype='object')

In [ ]:
dfs['price'].value_counts()  # zliczamy ilość elementów o tych samych wartościach z kolumny 'price'

price
prod1    2
prod2    2
prod3    1
Name: count, dtype: int64

In [ ]:
z = dfs['price'] # zawartość kolumny z nagłówkiem price
z
#z.value_counts()

0    prod1
1    prod3
2    prod2
3    prod1
4    prod2
Name: price, dtype: object

In [ ]:
dfs[['price', 'one']] # ograniczenie zbioru do wybranych nazw kolumn 'price', 'one' z tabeli

   price    one
0  prod1      1
1  prod3     10
2  prod2    100
3  prod1   1000
4  prod2  10000

In [ ]:
dfs[0:3] # selekcja wybranych wierszy tabeli data np: 0,1,2

   one  two  price
0    1    2  prod1
1   10   20  prod3
2  100  200  prod2

## Metoda: groupby
##### metoda grupuje dane tabelaryczne względem kolumny, na wyodrębnionych w ten sposób podgrupach/podzbiorach wykonuje rónocześnie zadeklarowaną operację

In [ ]:
dfPrice = dfs.groupby('price')  # grupujemy dane po kolumnie z nagłówkiem 'price'

In [ ]:
dfPrice.ngroups  # sprawdzenie liczby utworzonych podzbiorów <=> liczba kategorii w kolumnie 'price'

3

In [ ]:
dfPrice.groups  # podstawowe informacje o typach danych wewnątrz ramki danych

{'prod1': [0, 3], 'prod2': [2, 4], 'prod3': [1]}

In [ ]:
dfPrice.get_group('prod1') # wydzielenie podzbioru danych 'prod1'

    one   two  price
0     1     2  prod1
3  1000  2000  prod1

In [ ]:
dfPrice.describe()  # tabela podstawowych metryk statystyccznych zebranych dla poszczególnych podzbiorów z kolumny price

        one                                                                 \
      count    mean          std    min      25%     50%      75%      max
price
prod1   2.0   500.5   706.399674    1.0   250.75   500.5   750.25   1000.0
prod2   2.0  5050.0  7000.357134  100.0  2575.00  5050.0  7525.00  10000.0
prod3   1.0    10.0          NaN   10.0    10.00    10.0    10.00     10.0

        two
      count    mean          std    min    25%     50%     75%     max
price
prod1   2.0  1001.0  1412.799349    2.0  501.5  1001.0  1500.5  2000.0
prod2   2.0  1100.0  1272.792206  200.0  650.0  1100.0  1550.0  2000.0
prod3   1.0    20.0          NaN   20.0   20.0    20.0    20.0    20.0

In [ ]:
dfPrice.sum()   # sumowanie wartości obiektów po kolumnach dla poszczególnych podzbiorów

         one   two
price
prod1   1001  2002
prod2  10100  2200
prod3     10    20

In [ ]:
dfPrice.mean()  # srednia z kolumn

          one     two
price
prod1   500.5  1001.0
prod2  5050.0  1100.0
prod3    10.0    20.0

### Przykłady grupowania danych po wielu kolumnach

In [ ]:
grouped = dfs.groupby(['price', 'one'])

In [ ]:
print(grouped.get_group)

<bound method BaseGroupBy.get_group of <pandas.core.groupby.generic.DataFrameGroupBy object at 0x7a514d92f690>>

In [ ]:
print(grouped.sum())

              two
price one
prod1 1         2
      1000   2000
prod2 100     200
      10000  2000
prod3 10       20

In [ ]:
print(grouped.sum().index)

MultiIndex([('prod1',     1),
            ('prod1',  1000),
            ('prod2',   100),
            ('prod2', 10000),
            ('prod3',    10)],
           names=['price', 'one'])

### Praca na danych z pliku: zapis danych do pliku


The pandas I/O API is a set of top level reader functions accessed like pd.read_csv() that generally return a pandas object.

* read_csv
* read_excel
* read_hdf
* read_sql
* read_json
* read_msgpack (experimental)
* read_html
* read_gbq (experimental)
* read_stata
* read_sas
* read_clipboard
* read_pickle
The corresponding writer functions are object methods that are accessed like df.to_csv()

* to_csv
* to_excel
* to_hdf
* to_sql
* to_json
* to_msgpack (experimental)
* to_html
* to_gbq (experimental)
* to_stata
* to_clipboard
* to_pickle###  Praca na danych z pliku: odczyt danych z pliku

Sposób 1: wczytanie danych jeśli pracujesz z danymi na dysku google

In [ ]:
from google.colab import drive
drive.mount('/content/drive')    # podłączenie zasobów z dysku Google

In [ ]:
import os
import pandas as pd
folder_path = '/content/drive/MyDrive/Colab Notebooks/dataset/'
data = pd.read_excel(os.path.join(folder_path, 'titanic_train.xlsx'))
data.shape

Sposób 2: wczytanie danych jeśli pracujesz lokalnie

In [ ]:
#os.path.join(folder_path, 'titanic_train.xlsx')
#e:/DYDAKTYKA/Python/laboratorium/titanic_train.xlsx

#data = pd.read_excel('titanic_train.xlsx')  # tak wczytujemy dane z pliku jeśli jest w folderze roboczym
#data = pd.read_csv( 'movies.csv')

In [ ]:
data.head()  # metoda .head wyświetla dla wszystkich kolumn 5 pierwszych wierszy

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Praca na danych z pliku: zapis danych do pliku

In [ ]:
############# składnia funkcji dla plików z rozszerzeniem *.csv
# data.to_csv(path_or_buf=None, sep=',', na_rep='', float_format=None, columns=None,
#            header=True, index=True, index_label=None, mode='w', encoding=None,
#            compression=None, quoting=None, quotechar='"', line_terminator='\n',
#            chunksize=None, tupleize_cols=False, date_format=None, doublequote=True,
#            escapechar=None, decimal='.', **kwds)

In [ ]:
############## składnia funkcji dla plików z rozszerzeniem *.xlsx
# data.to_excel(excel_writer, sheet_name='Sheet1', na_rep='', float_format=None, columns=None,
#              header=True, index=True, index_label=None, startrow=0, startcol=0, engine=None,
#              merge_cells=True, encoding=None, inf_rep='inf', verbose=True)

In [ ]:
dataTitanic = data
folder_path = ''
data.to_excel(os.path.join(folder_path, 'titanic_copy.xlsx')) # zapis do pliku *.xlsx
data.to_csv(os.path.join(folder_path, 'titanic_copy.csv'), index=False)    # zapis do pliku *.csv

### Zadanie 1
#### Wykorzystując dane z pliku titanic.csv:
#### a) wypisz: pierwsze 3 kolumny, wiersze od 4 do 9,
#### b) wyznacz średnią wieku pasażerów statku
#### c) określ ile osób przeżyło katastrofę statku
#### d) określ statystyki podstawowe dla 2 grup/klas: male i female
#### e) ilu pasażerów podróżowało klasą 1 ilu 3

In [6]:
import pandas as pd
import os

folder_path = '/content/drive/MyDrive/Colab Notebooks/data/'
data = pd.read_csv(os.path.join(folder_path, 'titanic_train.csv'))

print(data.iloc[3:9, 0:3])

sredni_wiek = data['Age'].mean()
print(sredni_wiek)

liczba_ocalalych = data['Survived'].sum()
print(liczba_ocalalych)

print(data.groupby('Sex')['Age'].describe())

liczniki_klas = data['Pclass'].value_counts()
print(liczniki_klas.get(1, 0))
print(liczniki_klas.get(3, 0))

   PassengerId  Survived  Pclass
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
29.69911764705882
342
        count       mean        std   min   25%   50%   75%   max
Sex
female  261.0  27.915709  14.110146  0.75  18.0  27.0  37.0  63.0
male    453.0  30.726645  14.678201  0.42  21.0  29.0  39.0  80.0
216
491

## Metody .loc i .iloc - służą do selekcji danych
#### składnia:  nazwaObiektu.loc[numbersRows, nameColumns]      oraz   nazwaObiektu.iloc[numbersRows, numbersColumns]

#### Zadanie 2 Zapoznaj się z przykładami działania metod .loc oraz .iloc

In [ ]:
# print(data.loc[5])  # wyświetl dane 6 wiersz i wszystkie kolumny
# print(data.loc[5:10]) # wyświetl 6,...,9 wiersze i wszystkie kolumny
# print(data.loc[5, 'Name']) # wyświetl 6 wiersz z kolumny 'Name'
# print(data.loc[5:10, 'Name'])  # wyświetl 6,...,9 wiersze z kolumny 'Name'
# print(data.columns)
# print(data.loc[5:10, :'Pclass']) # wyświetl 6,...,10 wiersze i wszystkie kolumny poprzedzające kolumne 'Pclass'
# print(data.loc[5:10, ['Name', 'Survived']]) # wyświetl 6,...,10 wiersze i kolumny 'Name', 'Pclass', 'Survived'

                                                 Name  Survived
5                                    Moran, Mr. James         0
6                             McCarthy, Mr. Timothy J         0
7                      Palsson, Master. Gosta Leonard         0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         1
9                 Nasser, Mrs. Nicholas (Adele Achem)         1
10                    Sandstrom, Miss. Marguerite Rut         1

In [ ]:
#print(data.loc[5])  # wyświetl dane 6 wiersz i wszystkie kolumny
#print(data.loc[5:10]) # wyświetl 6,...,9 wiersze i wszystkie kolumny
# print(data.loc[5, 'Name']) # wyświetl 6 wiersz z kolumny 'Name'
# print(data.loc[5:10, 'Name'])  # wyświetl 6,...,9 wiersze z kolumny 'Name'
# print(data.columns)
# print(data.loc[5:10, :'Pclass']) # wyświetl 6,...,10 wiersze i wszystkie kolumny poprzedzające kolumne 'Pclass'
# print(data.loc[5:10, ['Name', 'Pclass', 'Survived']]) # wyświetl 6,...,10 wiersze i kolumny 'Name', 'Pclass', 'Survived'

In [ ]:
# print(data.iloc[1])
# print(data.iloc[5:10])
# print(data.iloc[5, 3])  # dane: 5 wiersz 3 kolumna
# print(data.iloc[5:10, 3])
# print(data.iloc[5:10, :3])
# print(data.iloc[range(0, 50, 5), [1, 3]]) # dane: wiersze od 0 do 50 z krokiem 5, kolumny: 1, 3
# print(data.iloc[:50:5, [1, 3]]) # analog do formuły powyżej
# print(data.iloc[-10:]) # minus oznacza liczenie od końca tu wyświetl od 10 wiersza od końca
# print(data.Pclass.max()) # Wartość max i min dla kolumny Pclass
# print(data.Pclass.min())
# print(data.Pclass.sum()) # Wartość sumy dla kolumny Pclass
# print(data['Cabin'])
#print(data.Cabin.fillna(0)) # wstaw 0 w rekordy w których brakuje danych czyli jest NaN w kolumnie Cabin

#### Zadanie 3
#### Korzystając z danych z pliku titanic:
#### a) Podaj wiek najmłodszego pasażera statku
#### b) imputacja danych: podstaw wartość średnią za NaN w kolumnie Age
#### c) wyświetl wiersze 2,4,30 i tylko 3 kolumny Age Name Sex

In [8]:
import pandas as pd
import os

folder_path = '/content/drive/MyDrive/Colab Notebooks/data/'
data = pd.read_csv(os.path.join(folder_path, 'titanic_train.csv'))

najmlodszy = data['Age'].min()
print(najmlodszy)

srednia_wieku = data['Age'].mean()
data['Age'] = data['Age'].fillna(srednia_wieku)
print(srednia_wieku)

wybrane_dane = data.loc[[2, 4, 30], ['Age', 'Name', 'Sex']]
print(wybrane_dane)

0.42
29.69911764705882
     Age                      Name     Sex
2   26.0    Heikkinen, Miss. Laina  female
4   35.0  Allen, Mr. William Henry    male
30  40.0  Uruchurtu, Don. Manuel E    male

#### Zadanie 4  Zapoznaj się z warunkową selekcją zmiennych

In [ ]:
# print(data['Pclass'] == 3) # określa które rekordy/wiersze kolumny Pclass mają bilet klasy 3
#print(data.loc[data['Pclass'] == 3]) # wyświetla tylko te wiersze dla których w kolumnie Pclass jest bilet klasy 3
#print(data[data['Pclass'] == 3]) # analog powyższej formuły
#print(data[data['Cabin'].isin(['C85', 'C123'])])  # szukanie w kolumnie 'Cabin' konkretnych elementów/wartości tj.'C85', 'C123'
#print(data[(data['Cabin'] == 'C123') & (data['Pclass']==1)]) # wiele warunków równocześnie  & => odpowiednik and

print(data[(data['Pclass'] == 1) & (data['Sex'] == 'female')].shape)
#print(data['Pclass'] == 1)

(94, 12)

In [ ]:
#print(data)
print(data.columns)

In [ ]:
print(data[data['Pclass'] == 1].shape)

In [ ]:
from pandas.core.groupby.groupby import get_groupby
from numpy.core.fromnumeric import shape
from pandas.core.groupby.groupby import get_groupby
from pandas.core.groupby import groupby

dane_sel = data.groupby(['Sex'])
dane_sel.describe()
#data_female = dane_sel.get_group('female')

#data_female.shape

/tmp/ipykernel_14023/3365719402.py:2: DeprecationWarning: numpy.core.fromnumeric is deprecated and has been renamed to numpy._core.fromnumeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.fromnumeric.shape.
  from numpy.core.fromnumeric import shape

       PassengerId                                                             \
             count        mean         std  min     25%    50%     75%    max
Sex
female       314.0  431.028662  256.846324  2.0  231.75  414.5  641.25  889.0
male         577.0  454.147314  257.486139  1.0  222.00  464.0  680.00  891.0

       Survived            ... Parch        Fare                              \
          count      mean  ...   75%  max  count       mean        std   min
Sex                        ...
female    314.0  0.742038  ...   1.0  6.0  314.0  44.479818  57.997698  6.75
male      577.0  0.188908  ...   0.0  5.0  577.0  25.523893  43.138263  0.00


              25%   50%    75%       max
Sex
female  12.071875  23.0  55.00  512.3292
male     7.895800  10.5  26.55  512.3292

[2 rows x 56 columns]

In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
folder_path = '/content/drive/MyDrive/Colab Notebooks/data/'

dfs = pd.read_excel(os.path.join(folder_path, 'titanic_train.xlsx'))

dfData = dfs.groupby('Age')
dfData.mean('Age')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

       PassengerId  Survived  Pclass  SibSp  Parch      Fare
Age
0.42         804.0       1.0     3.0    0.0    1.0    8.5167
0.67         756.0       1.0     2.0    1.0    1.0   14.5000
0.75         557.5       1.0     3.0    2.0    1.0   19.2583
0.83         455.5       1.0     2.0    0.5    1.5   23.8750
0.92         306.0       1.0     1.0    1.0    2.0  151.5500
...            ...       ...     ...    ...    ...       ...
70.00        709.5       0.0     1.5    0.5    0.5   40.7500
70.50        117.0       0.0     3.0    0.0    0.0    7.7500
71.00        295.5       0.0     1.0    0.0    0.0   42.0792
74.00        852.0       0.0     3.0    0.0    0.0    7.7750
80.00        631.0       1.0     1.0    0.0    0.0   30.0000

[88 rows x 6 columns]

#### Zadanie 5
#### a) wyswietl dane pasażerów którzy mają wiek poniżej 25 lat i bilet klasy 2 zapisz uzyskane do pliku na dysk
#### b) wyświetl ile osób podróżowało statkiem, podaj w/w dane z podziałem na kategorie np.: płeć, klasa biletu, wiek (grupy co 10 lat)
#### c) określ ile osób przeżyło katastrofę statku

In [9]:
import pandas as pd
import os

folder_path = '/content/drive/MyDrive/Colab Notebooks/data/'
data = pd.read_csv(os.path.join(folder_path, 'titanic_train.csv'))

filtr = (data['Age'] < 25) & (data['Pclass'] == 2)
pasazerowie_wybrani = data[filtr]
print(pasazerowie_wybrani.head())

pasazerowie_wybrani.to_csv('pasazerowie_ponizej_25_klasa_2.csv', index=False)
print("\nDane zostały zapisane do pliku: pasazerowie_ponizej_25_klasa_2.csv")

print(data)

print(data['Sex'].value_counts())

print(data['Pclass'].value_counts().sort_index())

bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
data['Age_Group'] = pd.cut(data['Age'], bins=bins)
print(data['Age_Group'].value_counts().sort_index())

przezylo = data['Survived'].sum()
print(przezylo)

    PassengerId  Survived  Pclass                                      Name  \
9            10         1       2       Nasser, Mrs. Nicholas (Adele Achem)
43           44         1       2  Laroche, Miss. Simonne Marie Anne Andree
56           57         1       2                         Rugg, Miss. Emily
58           59         1       2              West, Miss. Constance Mirium
72           73         0       2                      Hood, Mr. Ambrose Jr

       Sex   Age  SibSp  Parch         Ticket     Fare Cabin Embarked
9   female  14.0      1      0         237736  30.0708   NaN        C
43  female   3.0      1      2  SC/Paris 2123  41.5792   NaN        C
56  female  21.0      0      0     C.A. 31026  10.5000   NaN        S
58  female   5.0      1      2     C.A. 34651  27.7500   NaN        S
72    male  21.0      0      0   S.O.C. 14879  73.5000   NaN        S

Dane zostały zapisane do pliku: pasazerowie_ponizej_25_klasa_2.csv
     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]
Sex
male      577
female    314
Name: count, dtype: int64
Pclass
1    216
2    184
3    491
Name: count, dtype: int64
Age_Group
(0, 10]      64
(10, 20]    115
(20, 30]    230
(30, 40]    155
(40, 50]     86
(50, 60]     42
(60, 70]     17
(70, 80]      5
(80, 90]      0
Name: count, dtype: int64
342

#### Zadanie 6
#### Korzystając z daneych o filmach movies.csv
#### a) określ ile filmów nakręcono w każdym roku
#### b) określ który film miał najwięcej lajków na facebook-u
#### c) podziel zbiór ze względu na kategorię country lub color i określ dla każdej kategorii liczbę filmów o budżecie > 240mln
#### d) jaki film wykonany w kolorze miał największy budżet?
#### e) Czy w zbiorze znajdują się dane dla filmu Piraci z karaibów? Jeśli tak to ile kosztował ten film i kto był jego reżyserem
#### f) Jaki film miał największy budżet

In [11]:
data2 = pd.read_csv(os.path.join(folder_path, 'movies.csv'))
import pandas as pd
filmy_rok = data2['title_year'].value_counts().sort_index()
print(filmy_rok)

idx_lajki = data2['movie_facebook_likes'].idxmax()
film_lajki = data2.loc[idx_lajki, 'movie_title']
print(film_lajki)

bogate_filmy = data2[data2['budget'] > 240000000]
print(bogate_filmy.groupby('country').size())

kolorowe = data2[data2['color'] == 'Color']
idx_kolor_budzet = kolorowe['budget'].idxmax()
film_kolor_budzet = kolorowe.loc[idx_kolor_budzet, 'movie_title']
print(film_kolor_budzet)

piraci = data2[data2['movie_title'].str.contains('Pirates of the Caribbean', case=False, na=False)]
if not piraci.empty:
    print(piraci[['movie_title', 'budget', 'director_name']])
else:
    print("Nie znaleziono danych dla tego filmu.")

idx_max_b = data2['budget'].idxmax()
print(data2.loc[idx_max_b, 'movie_title'])

title_year
1916.0      1
1920.0      1
1925.0      1
1927.0      1
1929.0      2
         ...
2012.0    221
2013.0    237
2014.0    252
2015.0    226
2016.0    106
Name: count, Length: 91, dtype: int64
Interstellar
country
China           1
France          1
Hungary         1
India           2
Japan           4
New Zealand     1
South Korea     2
Spain           1
Thailand        2
UK              2
USA            10
dtype: int64
The Host
                                           movie_title       budget  \
1             Pirates of the Caribbean: At World's End  300000000.0
13          Pirates of the Caribbean: Dead Man's Chest  225000000.0
18         Pirates of the Caribbean: On Stranger Tides  250000000.0
205  Pirates of the Caribbean: The Curse of the Bla...  140000000.0

      director_name
1    Gore Verbinski
13   Gore Verbinski
18     Rob Marshall
205  Gore Verbinski
The Host

### Łączenie danych tabelarycznych (concatenate)
funkcja concat() - domyślnie względem wierszy

pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,
          keys=None, levels=None, names=None, verify_integrity=False,
          copy=True)

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3'],
                     'C': ['C0', 'C1', 'C2', 'C3'],
                     'D': ['D0', 'D1', 'D2', 'D3']},
                     index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                     'B': ['B4', 'B5', 'B6', 'B7'],
                     'C': ['C4', 'C5', 'C6', 'C7'],
                     'D': ['D4', 'D5', 'D6', 'D7']},
                      index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                     'B': ['B8', 'B9', 'B10', 'B11'],
                     'C': ['C8', 'C9', 'C10', 'C11'],
                     'D': ['D8', 'D9', 'D10', 'D11']},
                     index=[8, 9, 10, 11])

frame = [df1, df2, df3]

In [ ]:
pd.concat(frame)

In [ ]:
df4 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
                  'D': ['D2', 'D3', 'D6', 'D7'],
                  'F': ['F2', 'F3', 'F6', 'F7']},
                 index=[2, 3, 6, 7])

In [ ]:
pd.concat([df1, df4], axis=1)   # łączenie ze wskazaniem pozycji w tabeli

In [ ]:
pd.concat([df1, df4], axis=1, join='inner')

Funkcja merge() - względem kolumn, indeksów
merge(right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False)

In [ ]:
 left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                      'A': ['A0', 'A1', 'A2', 'A3'],
                      'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                       'C': ['C0', 'C1', 'C2', 'C3'],
                       'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
# kluczowy argument to how który określa sposób łącznie danych, mamy warianty:
#left,           right, outer, inner
pd.merge(left, right, on='key')